### ISSUE TITLE
kafkaspout無法實時讀取訊息, 出現錯誤

### ISSUE THREAD

**Issue by RonHsu** [smartloli/qa-hadoop#1]
在粗體字, 讀到訊息後 ,出現後續的錯誤 ,請幫忙解答, 謝謝.

**-----8.Index:30 messages from kafka:{"StationID": "FM3042"}**
16005 [Thread-10-spout] INFO  b.s.d.task - Emitting: spout default [{"StationID": "FM3042"}]
16565 [main] INFO  b.s.d.nimbus - [req 1] Access from:  principal: op:killTopology
16577 [main] INFO  b.s.d.nimbus - Delaying event :remove for 60 secs for firstTopo-1-1463996026
16660 [main] INFO  b.s.d.nimbus - Shutting down master
16669 [ProcessThread(sid:0 cport:-1):] INFO  o.a.s.s.o.a.z.s.PrepRequestProcessor - Processed session termination for sessionid: 0x154dcf683e70001
16718 [main] INFO  o.a.s.s.o.a.z.ZooKeeper - Session: 0x154dcf683e70001 closed
16719 [main] INFO  b.s.d.nimbus - Shut down master
16720 [main-EventThread] INFO  o.a.s.s.o.a.z.ClientCnxn - EventThread shut down
**16725 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2000] WARN  o.a.s.s.o.a.z.s.NIOServerCnxn - caught end of stream exception
org.apache.storm.shade.org.apache.zookeeper.server.ServerCnxn$EndOfStreamException: Unable to read additional data from client sessionid 0x154dcf683e70001, likely client has closed socket
    at org.apache.storm.shade.org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228) [storm-core-0.10.0.jar:0.10.0]
    at org.apache.storm.shade.org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208) [storm-core-0.10.0.jar:0.10.0]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]**
16726 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2000] INFO  o.a.s.s.o.a.z.s.NIOServerCnxn - Closed socket connection for client /127.0.0.1:59619 which had sessionid 0x154dcf683e70001
16730 [ProcessThread(sid:0 cport:-1):] INFO  o.a.s.s.o.a.z.s.PrepRequestProcessor - Processed session termination for sessionid: 0x154dcf683e70004
16798 [main] INFO  o.a.s.s.o.a.z.ZooKeeper - Session: 0x154dcf683e70004 closed
16798 [main-EventThread] INFO  o.a.s.s.o.a.z.ClientCnxn - EventThread shut down
**16801 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2000] WARN  o.a.s.s.o.a.z.s.NIOServerCnxn - caught end of stream exception
org.apache.storm.shade.org.apache.zookeeper.server.ServerCnxn$EndOfStreamException: Unable to read additional data from client sessionid 0x154dcf683e70004, likely client has closed socket
    at org.apache.storm.shade.org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228) [storm-core-0.10.0.jar:0.10.0]
    at org.apache.storm.shade.org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208) [storm-core-0.10.0.jar:0.10.0]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]**
16804 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2000] INFO  o.a.s.s.o.a.z.s.NIOServerCnxn - Closed socket connection for client /127.0.0.1:59628 which had sessionid 0x154dcf683e70004
16805 [ProcessThread(sid:0 cport:-1):] INFO  o.a.s.s.o.a.z.s.PrepRequestProcessor - Processed session termination for sessionid: 0x154dcf683e70005
**16877 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2000] WARN  o.a.s.s.o.a.z.s.NIOServerCnxn - caught end of stream exception
org.apache.storm.shade.org.apache.zookeeper.server.ServerCnxn$EndOfStreamException: Unable to read additional data from client sessionid 0x154dcf683e70005, likely client has closed socket
    at org.apache.storm.shade.org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228) [storm-core-0.10.0.jar:0.10.0]
    at org.apache.storm.shade.org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208) [storm-core-0.10.0.jar:0.10.0]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]**
16878 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2000] INFO  o.a.s.s.o.a.z.s.NIOServerCnxn - Closed socket connection for client /127.0.0.1:59631 which had sessionid 0x154dcf683e70005
16876 [main] INFO  o.a.s.s.o.a.z.ZooKeeper - Session: 0x154dcf683e70005 closed
16884 [main] INFO  b.s.d.supervisor - Shutting down 96f5d3a8-8e08-409a-85a7-ef2a93f6b2e5:9849641d-a683-464d-8e6c-f70df1d6184c
16886 [main] INFO  b.s.config - GET worker-user 9849641d-a683-464d-8e6c-f70df1d6184c
16908 [main-EventThread] INFO  o.a.s.s.o.a.z.ClientCnxn - EventThread shut down
16914 [main] INFO  b.s.process-simulator - Killing process e6d5c7f7-d75a-453b-a94b-1819188bba8c
16915 [main] INFO  b.s.d.worker - Shutting down worker firstTopo-1-1463996026 96f5d3a8-8e08-409a-85a7-ef2a93f6b2e5 1024
16915 [main] INFO  b.s.d.worker - Shutting down receive thread
16916 [main] INFO  b.s.m.loader - Shutting down receiving-thread: [firstTopo-1-1463996026, 1024]
16916 [main] INFO  b.s.m.loader - Waiting for receiving-thread:[firstTopo-1-1463996026, 1024] to die
16923 [main] INFO  b.s.m.loader - Shutdown receiving-thread: [firstTopo-1-1463996026, 1024]
16923 [main] INFO  b.s.d.worker - Shut down receive thread
16923 [main] INFO  b.s.d.worker - Terminating messaging context
16924 [main] INFO  b.s.d.worker - Shutting down executors
16924 [main] INFO  b.s.d.executor - Shutting down executor spout:[2 2]
16925 [Thread-9-disruptor-executor[2 2]-send-queue] INFO  b.s.util - Async loop interrupted!
16926 [Thread-8-worker-receiver-thread-0] INFO  b.s.m.loader - Receiving-thread:[firstTopo-1-1463996026, 1024] received shutdown notice
16928 [Thread-10-spout] INFO  b.s.util - Async loop interrupted!

**Comment by smartloli** [comment]
能否贴下你这部分实现的代码，另外，你的 ZooKeeper 集群是否运行正常。

**Comment by RonHsu** [comment]
zookeeper的log出現以下訊息, 因為程式仍可以取得資料, 故不確定是否這個原因造成的.
`2016-05-24 15:30:03,031 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@362] - Exception causing close of session 0x154b80db7cc02ea due to java.io.IOException: Connection reset by peer`

代碼如下, 請您幫忙囉, 謝謝
package IAC.Storm;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import kafka.consumer.ConsumerConfig;
import kafka.consumer.ConsumerIterator;
import kafka.consumer.KafkaStream;
import kafka.javaapi.consumer.ConsumerConnector;
import backtype.storm.spout.SpoutOutputCollector;
import backtype.storm.task.TopologyContext;
import backtype.storm.topology.IRichSpout;
import backtype.storm.topology.OutputFieldsDeclarer;
import backtype.storm.tuple.Fields;
import backtype.storm.tuple.Values;

public class KafkaSpouttest implements IRichSpout {

```
private SpoutOutputCollector collector;
private ConsumerConnector consumer;
private String topic;
static long TotalCount;

public KafkaSpouttest(String topic) {
    System.out.println("-----1.KafkaSpouttest_topic");
    this.topic = topic;
}
public Map<String, Object> getComponentConfiguration() {
    System.out.println("-----2.getComponentConfiguration");
    return null;
}
public void declareOutputFields(OutputFieldsDeclarer declarer) {
    System.out.println("-----3.declareOutputFields");
    declarer.declare(new Fields("DataSet"));
}
public void open(Map conf, TopologyContext context, SpoutOutputCollector collector) {
    System.out.println("-----4.open");
    this.collector = collector;
}
public void activate() {
    System.out.println("-----5.activate");
    System.out.println("-----ConnectTime: " + System.currentTimeMillis());
    // Create the connection to the cluster
    consumer =kafka.consumer.Consumer.createJavaConsumerConnector(createConsumerConfig());  
    Map<String,Integer> topickMap = new HashMap<String, Integer>();  
    topickMap.put(topic, 1);

    // create 4 partitions of the stream for topic “test”, to allow 4 threads to consume
    System.out.println("-----7.Results topic:" +topic);   
    Map<String, List<KafkaStream<byte[],byte[]>>> streamMap=consumer.createMessageStreams(topickMap);  
    KafkaStream<byte[],byte[]>stream = streamMap.get(topic).get(0);
    ConsumerIterator<byte[],byte[]> it =stream.iterator();

    TotalCount = 1;
    System.out.println("-----FetchStratTime: " + System.currentTimeMillis());

    while(it.hasNext()){
         String value =new String(it.next().message());

         System.out.println("-----8.Index:" +TotalCount +" messages from kafka:" +value);
         TotalCount += 1;
         collector.emit(new Values(value));

    }  
}
private static ConsumerConfig createConsumerConfig() {  
    System.out.println("-----6.createConsumerConfig");
    Properties props = new Properties();  
    // set zookeeper's IP of kafka
    //props.put("zookeeper.connect","m1:2181,m2:2181,s1:2181,s2:2181");  
    props.put("zookeeper.connect","localhost:2181");
    // set group id
    props.put("group.id", "yyyyyy");  
    props.put("auto.commit.interval.ms", "1000");
    props.put("zookeeper.session.timeout.ms","10000");  
    props.put("auto.offset.reset","smallest"); // offset earliest/latest/none

    return new ConsumerConfig(props);
}
public void nextTuple() {
    System.out.println("-----nextTuple");
}
public void ack(Object msgId) {
    System.out.println("-----ack");
}

public void close() {
    System.out.println("-----close");
}

public void deactivate() {
    System.out.println("-----deactivate");
}

public void fail(Object msgId) {
    System.out.println("-----fail");
}
```

}

**Comment by smartloli** [comment]
代码实现没什么问题，检查一下你的 ZooKeeper 集群的健康状态。

**Comment by RonHsu** [comment]
重啟zookeeper後, 在log中出現下列訊息, 請問該如何排除?

> 2016-05-24 20:54:25,640 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@489] - Processed session termination for sessionid: 0x154e2d2dba50005
> 2016-05-24 20:54:25,686 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1008] - Closed socket connection for client /127.0.0.1:57258 which had sessionid 0x154e2d2dba50005
> 2016-05-24 20:54:26,006 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@357] - caught end of stream exception
> EndOfStreamException: Unable to read additional data from client sessionid 0x154e2d2dba50001, likely client has closed socket
>         at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:230)
>         at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:203)
>         at java.lang.Thread.run(Thread.java:745)
> 2016-05-24 20:54:26,011 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1008] - Closed socket connection for client /0:0:0:0:0:0:0:1:44244 which had sessionid 0x154e2d2dba50001
> 2016-05-24 20:54:26,011 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@357] - caught end of stream exception
> EndOfStreamException: Unable to read additional data from client sessionid 0x154e2d2dba50002, likely client has closed socket
>         at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:230)
>         at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:203)
>         at java.lang.Thread.run(Thread.java:745)
> 2016-05-24 20:54:26,015 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1008] - Closed socket connection for client /127.0.0.1:57253 which had sessionid 0x154e2d2dba50002
> 2016-05-24 20:54:26,016 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@357] - caught end of stream exception
> EndOfStreamException: Unable to read additional data from client sessionid 0x154e2d2dba50003, likely client has closed socket
>         at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:230)
>         at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:203)
>         at java.lang.Thread.run(Thread.java:745)
> 2016-05-24 20:54:26,017 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1008] - Closed socket connection for client /127.0.0.1:57254 which had sessionid 0x154e2d2dba50003

**Comment by smartloli** [comment]
ZooKeeper 节点对应的 myid 文件配置没问题吧？

**Comment by RonHsu** [comment]
只有一個節點, 所以沒有設定myid, 單個節點也要設定myid嗎？

**Comment by smartdengjie** [comment]
参考以下示例代码的内容，亲测通过。
[demo.zip](https://github.com/smartloli/qa-hadoop/files/281308/demo.zip)

**Comment by smartloli** [comment]
参考以下示例代码的内容。
[demo.zip](https://github.com/smartloli/qa-hadoop/files/281316/demo.zip)

**Comment by RonHsu** [comment]
了解, 謝謝幫忙, 解決一個大問題
